# This file was generated by GoReleaser. DO NOT EDIT.
cask "dex" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "4d5718e54dd78b80fda754c38c36946e985e1972a644852194a8d0a2ec9c6093"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f550374d31e6b7db277f5323f936f89f52600e6cee1de9aa70562481342ade11"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "72db2736cc4947b020ede951db886c2ef3af69110d891fb9d5a22b7d85bb120d"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eec6a34dad7f2d958267d5e5ec4dedeb6b6b7c7e0bb96bef06a476bf2b080d88"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dex"
  desc "IRC/TUI client for dexchat"
  homepage "https://github.com/dexchat/dex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dex"

  # No zap stanza required

  caveats <<~EOS
    If macOS blocks dexchat, enable it by running the following command:

      xattr -d com.apple.quarantine "$(command -v dex)"
  EOS
end
