# This file was generated by GoReleaser. DO NOT EDIT.
cask "dex" do
  version "0.1.5-test"

  on_macos do
    on_arm do
      sha256 "df9e107b5a3f351cad3785abf40ecb625df19b8d769cb05252460a0ab5e79ef7"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa222be02258d99650eb0967c3d66b25afcbcfd58106c73279f01b7bb4fa70d5"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b633f152fb7fdc8fb25653c333a005a1b74bacbd4a0d91e443db54cc9c09d61f"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ac53fa6f53c4578e21f01322fabcd5ca6b497a80d2508cf74428a5e4576274e0"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dex"
  desc "IRC/TUI client for DexChat"
  homepage "https://github.com/dexchat/dex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dex"

  # No zap stanza required
end
