# This file was generated by GoReleaser. DO NOT EDIT.
cask "dex" do
  version "0.0.0"

  on_macos do
    on_arm do
      sha256 "098966f157fba4a8122df02057d1dbdcd3207bfcc2f18711ddf6491947853749"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "400dc6da0767c779670c330c25684fbd720facfe552b0fcf622543b36c70033f"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f8db220b16ab8ea7c24567756f70636aa31e8b8f5b5dd55f7e3a38135edc9ae2"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "573d71e0d24a25cd2a353fa8b6575f4957f613841bb762fdcf7438d456e445a0"
      url "https://github.com/dexchat/dex/releases/download/v#{version}/dex_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dex"
  desc "IRC/TUI client for DexChat"
  homepage "https://github.com/dexchat/dex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dex"

  # No zap stanza required
end
